apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-appprotect-dos-arbitrator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-appprotect-dos-arbitrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: arb
  selector:
    {{- include "nginx-appprotect-dos-arbitrator.selectorLabels" . | nindent 4 }}
